### ISSUE TITLE
Next 13: Error After Import Geist Font -> SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by iamdevmarcos** [vercel/geist-font#27] opened 2023-10-29 12:31 UTC
**Font Name (Geist Sans/Geist Mono):**
- [x] Geist Sans
- [x] Geist Mono

**Description of the Issue:**
A compilation error occurred after installing and importing the Geist font.

**Steps to Reproduce:**
1. Install Geist font, using `npm i geist`
2. Import GeistSans or GeistMono in the top level at _app.tsx
3. Use GeistSans.className at `<main className="GeistSans.className" />`

**Screenshots:**

Error:

![image](https://github.com/vercel/geist-font/assets/92524722/5b279dae-90e5-4fa3-91de-645b229ed62c)

My _app.tsx file.

![image](https://github.com/vercel/geist-font/assets/92524722/f3e43841-f80e-465e-be22-722a4ccf9a08)

**Environment (please complete the following information):**
 - OS: [MacOS]
 - Version of the Font: [1.0.0]

**Additional Information**

- Next.js Version: [13.1.1]
- React Version: [18.2.0]

**Comment by Ethaan** [comment] 2023-10-30 02:27
FYI i noticed the same, but to get this font working i used the `localFont` like

```
const geist = localFont({
  src: [
    { path: "../public/fonts/Geist/Geist-Regular.otf", weight: "500" },
    { path: "../public/fonts/Geist/Geist-Medium.otf", weight: "600" },
    { path: "../public/fonts/Geist/Geist-SemiBold.otf", weight: "700" },
    { path: "../public/fonts/Geist/Geist-Bold.otf", weight: "800" },
    { path: "../public/fonts/Geist/Geist-Black.otf", weight: "900" },
  ],
  display: "swap",
  variable: "--font-geist-sans",
  fallback: ["inter"],
});
```


### For those using TailwindCSS

Extend the theme
```
extend: {
 fontFamily: {
   sans: ['var(--font-geist-sans)'],
 },
}
```

Then use it

`<div className={cn(geist.variable, "font-sans")}>`

**Comment by JohnPhamous** [comment] 2023-10-30 16:48
Thank for you trying out the font and reporting this. Closing this issue as this is a dupe of #13. We will fix this!

**Closed by JohnPhamous** 2023-10-30 16:48 UTC
Labels: bug
