### ISSUE TITLE
Support 100-900 scale for variable font weight in VSCode (Geist Mono)

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [vercel/geist-font#14] opened 2023-10-27 21:13 UTC
**Font Name (Geist Sans/Geist Mono):**
- [ ] Geist Sans
- [x] Geist Mono

**Description of the Issue:**
It seems like the 100-900 font weight scale doesn't work corretly in VSCode. 

**Steps to Reproduce:**
1. In user settings.json set `"editor.fontWeight": 1,` - you get a very thin font weight.
2. In user settings.json set `"editor.fontWeight": 100,` - you get a thicker font weight than 1.
Test with other values as needed.

**Expected Behavior:**
Every 100 increment value between  `"editor.fontWeight": 100,` and  `"editor.fontWeight": 900,` should have a different font weight going from very thin to very bold.

**Screenshots:**

**Environment (please complete the following information):**
 - OS: Windows 10 64bit
 - Software: VSCode
 - Version of the Font: 1.0

**Additional Context:**

**Comment by JohnPhamous** [comment] 2023-10-30 17:54
Thanks for reporting this! Closing this because it's a dupe of #12.

**Closed by JohnPhamous** 2023-10-30 17:54 UTC
Labels: bug
