### ISSUE TITLE
Default font weight too thin?

### ISSUE THREAD

**Issue by zieka** [vercel/geist-font#15] opened 2023-10-27 22:28 UTC
**Font Name (Geist Sans/Geist Mono):**
- [x] Geist Sans
- [x] Geist Mono

**Description of the Issue:**
The default font weight seems very thin.  I tried in VScode and Obsidian; both cases just switching to the fonts and no other changes resulted in a weight that seemed close to a browser system font of 200 or 300 which seems quite thin for default text in most applications.

**Steps to Reproduce:**
1. set either font as the default font of an application like vscode or obsidian
2. observe text

**Expected Behavior:**
Got very thin font weight as default.  Was expecting something similar to other fonts.

**Screenshots:**
<img width="244" alt="image" src="https://github.com/vercel/geist-font/assets/4691147/9efd5936-a5cd-45a3-8b68-9a71ab91c691">
<img width="299" alt="image" src="https://github.com/vercel/geist-font/assets/4691147/39bf91c2-9ebb-4c7a-8848-3ffb9d44a831">

**Environment (please complete the following information):**
 - MacOS sonoma
 - Obsidian Version 1.4.16 (Installer 1.4.14)

**Comment by axcellence** [comment] 2023-10-28 22:30
Yes, it seems that Thin is conflicting with Regular. When installing the fonts Thin is labelled Regular and both are checked. https://dropover.cloud/85c1d3#fe54d565-d31d-43dd-9cd2-630f6896e445

**Comment by JohnPhamous** [comment] 2023-10-30 17:52
Thank you for the feedback. Closing this because it's a dupe of #12.

**Closed by JohnPhamous** 2023-10-30 17:52 UTC
Labels: bug
