### ISSUE TITLE
Doesn't work in Storybook

### ISSUE THREAD

**Issue by BorisZubchenko** [vercel/geist-font#72] opened 2023-12-13 11:31 UTC
**Font Name (Geist Sans/Geist Mono):**
- [x] Geist Sans
- [x] Geist Mono

**Description of the Issue:**
Importing the font into Storybook breaks it. Importing fonts via `next/font` works fine, however.

**Steps to Reproduce:**
1. Create a Next app with Storybook
2. Create a rootCss variable
```tsx
import { GeistMono } from 'geist/font/mono'
import { GeistSans } from 'geist/font/sans'

import cs from '~/app/_lib/react/cs' // a utility to join classes

const rootCss = cs(
  GeistSans.variable,
  GeistMono.variable,
  'text-foreground max-w-full bg-background font-sans antialiased',
)

export default rootCss
```
3. Use it in Storybook's preview:
```tsx
import type { Preview } from '@storybook/react'

import '~/app/globals.css'

const preview = {
  decorators: [
    (Story) => <div className={rootCss}><Story/></div>
  ],
  // ...
} satisfies Preview

export default preview
```
4. Have an error:
```
next_font_local__WEBPACK_IMPORTED_MODULE_0___default(...) is not a function
TypeError: next_font_local__WEBPACK_IMPORTED_MODULE_0___default(...) is not a function
    at ./node_modules/.pnpm/geist@1.2.0_next@14.0.4/node_modules/geist/dist/mono.js (http://localhost:6006/vendors-node_modules_pnpm_babel_runtime_7_23_5_node_modules_babel_runtime_helpers_esm_defineP-4ea83d.iframe.bundle.js:19620:73)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:301:21)
    at ./app/_lib/react/root-css.tsx (http://localhost:6006/main.iframe.bundle.js:593:73)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:301:21)
    at ./.storybook/decorators/theme/index.tsx (http://localhost:6006/main.iframe.bundle.js:292:81)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:301:21)
    at ./.storybook/preview.tsx (http://localhost:6006/main.iframe.bundle.js:529:75)
```

**Expected Behavior:**
Should work

**Screenshots:**
![image](https://github.com/vercel/geist-font/assets/31354262/12f2e73b-1821-4426-87b3-84bd9307d500)

**Environment (please complete the following information):**
 - OS: N/A
 - Software: Next.js+Storybook
 - Version of the Font: 1.2.0

**Comment by AugustinMauroy** [comment] 2024-01-04 14:10
same issue @BorisZubchenko have you found any solution ?

**Comment by BorisZubchenko** [comment] 2024-01-05 08:55
Unfortunately, no. I've returned to Inter for now.

**Comment by AugustinMauroy** [comment] 2024-01-05 09:58
ok thanks I'ill do that

**Comment by igorgladkoborodov** [comment] 2024-02-02 06:11
Hi everyone. I used this workaround to make it work on my project:

1. Install and setup `@storybook/nextjs` as described here https://storybook.js.org/docs/8.0/get-started/nextjs

2. Setup `staticDirs` in `.storybook/main.ts`:
```typescript
  staticDirs: [
    {
      from: "../node_modules/geist/dist/fonts/geist-sans",
      to: "/fonts/geist-sans",
    },
    {
      from: "../node_modules/geist/dist/fonts/geist-mono",
      to: "/fonts/geist-mono",
    },
  ],
};
```

3. Use `localFont` directly in `.storybook/preview.tsx`:
```typescript
import localFont from "next/font/local";
import type { Preview } from "@storybook/react";

import "../src/app/globals.css";

const GeistSans = localFont({
  src: "../fonts/geist-sans/Geist-Variable.woff2",
  variable: "--font-geist-sans",
});

const GeistMono = localFont({
  src: "../fonts/geist-mono/GeistMono-Variable.woff2",
  variable: "--font-geist-mono",
});

const preview: Preview = {
  decorators: [
    (Story) => (
      <div className={`${GeistMono.variable} ${GeistSans.variable}`}>
        <Story />
      </div>
    ),
  ],
};

export default preview;
```

**Comment by Francois-Esquire** [comment] 2024-05-14 17:24
> [<img alt="@guidoferreyra" width="20" height="20" src="https://avatars.githubusercontent.com/u/1755590?s=40&amp;u=457c9be6e9bcefcc703fc1d3128b9bd0d7cf71d4&amp;v=4">](/guidoferreyra) [guidoferreyra](/guidoferreyra) added the [ where: package ](/vercel/geist-font/labels/where%3A%20package) label [Feb 23, 2024](#event-11903668447)
> [Gyozadaigaku](/Gyozadaigaku) added a commit to Gyozadaigaku/shadcn-design-system that referenced this issue [ Mar 31, 2024 ](#ref-commit-f549b05)
> [ <img alt="@Gyozadaigaku" width="20" height="20" src="https://avatars.githubusercontent.com/u/28142346?s=40&amp;u=62db31a338e937b0b18d8ddae2df77182066896c&amp;v=4"> ](/Gyozadaigaku)
> ` [💄 Use Geist Font](/Gyozadaigaku/shadcn-design-system/commit/f549b05343927ad6f69f3f0bd0a7737476b587da) ` …
> ` [f549b05](/Gyozadaigaku/shadcn-design-system/commit/f549b05343927ad6f69f3f0bd0a7737476b587da) `
> [<img alt="@Francois-Esquire" width="40" height="40" src="https://avatars.githubusercontent.com/u/12474067?s=80&amp;v=4">](/Francois-Esquire)
> 
> 
> #### Add a comment
> Comment
> Write
> Preview
> 
> 
> Add your comment here...
> 
> [ Markdown is supported ](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) 
> Paste, drop, or click to add files
> Comment
> Remember, contributions to this repository should follow its [security policy](/vercel/.github/blob/f6c4947de639d0fddc2b9bc2b0b50be515cd9657/SECURITY.md).
> Assignees
> No one assigned
> Labels
> [ bug ](/vercel/geist-font/labels/bug) [ where: package ](/vercel/geist-font/labels/where%3A%20package)
> Projects
> None yet
> Milestone
> No milestone
> Development
> No branches or pull requests
> 
> Notifications
> Customize
> 
> Subscribe
> You’re not receiving notifications from this thread.
> 
> 4 participants
> [ <img alt="@igorgladkoborodov" width="26" height="26" src="https://avatars.githubusercontent.com/u/9132?s=52&amp;v=4"> ](/igorgladkoborodov) [ <img alt="@guidoferreyra" width="26" height="26" src="https://avatars.githubusercontent.com/u/1755590?s=52&amp;v=4"> ](/guidoferreyra) [ <img alt="@BorisZubchenko" width="26" height="26" src="https://avatars.githubusercontent.com/u/31354262?s=52&amp;v=4"> ](/BorisZubchenko) [ <img alt="@AugustinMauroy" width="26" height="26" src="https://avatars.githubusercontent.com/u/97875033?s=52&amp;v=4">](/AugustinMauroy)

Although this didn't quite work for me, I used the `preview-head.html` to get this working with the same `staticDirs` config... don't like it, but it works. 

```html
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link
  href="https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&display=swap"
  rel="stylesheet"
/>
<style>
  @font-face {
    font-family: "Geist Sans";
    src: url("fonts/geist-sans/Geist-Variable.woff2");
  }
  @font-face {
    font-family: "Geist Mono";
    src: url("fonts/geist-mono/Geist-Variable.woff2");
  }
  .dm-serif-display-regular {
    font-family: "DM Serif Display", serif;
    font-weight: 400;
    font-style: normal;
  }
  .dm-serif-display-regular-italic {
    font-family: "DM Serif Display", serif;
    font-weight: 400;
    font-style: italic;
  }
  :root {
    --font-dm_serif_display: "DM Serif Display", serif;
    --font-geist-sans: "Geist Sans", sans-serif;
    --font-geist-mono: "Geist Mono", monospace;
  }
</style>
```

**Comment by JohnPhamous** [comment] 2024-07-01 20:26
I think this has the same root cause as https://github.com/vercel/geist-font/issues/59

Closing this as a duplicate of that.

**Closed by JohnPhamous** 2024-07-01 20:26 UTC
Labels: bug, where: package
